dbeaver/pro#1530 remove eclipse.ui dependency from draw2d & transfer theming to gef
eclipse/gef-classic pull request #163
Opened 2023-04-06 11:41 UTC by Destrolaric

2023-04-06 11:53 UTC, Destrolaric commented
`NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 5.15.0-1035-azure
`
I think there are issues present with the CI/CD.

2023-04-06 15:57 UTC, azoitl commented
@Destrolaric thx for the fix. I had a first look at the output of the windows and linux builds. The tests are back to where we were before the color management improvement. Will give it some tries on my machine tonight or tomorrow. I also have some changes for the failing tests that I would like to try with your PR.

2023-04-07 06:47 UTC, azoitl requested changes

2023-04-07 06:47 UTC, azoitl commented on org.eclipse.draw2d/src/org/eclipse/draw2d/BasicColorProvider.java
> + * Copyright (c) 2000, 2023 IBM Corporation and others.
As this is a sole contribution by you this line should be:
    2023 DBeaver Corporation

2023-04-07 06:47 UTC, azoitl commented on org.eclipse.draw2d/src/org/eclipse/draw2d/BasicColorProvider.java
> + *     Serge Rider - serge@dbeaver.com
In the other eclipse projects we do for first files:

  Georgii Gvinepadz, Serge Rider - initial API and implementation

2023-04-07 06:47 UTC, azoitl commented on org.eclipse.gef/src/org/eclipse/gef/ThemeConstants.java
> + * Copyright (c) 2000, 2023 IBM Corporation and others.
similar then above this copyright header should not feature IBM

2023-04-07 06:47 UTC, azoitl commented on org.eclipse.gef/src/org/eclipse/gef/GEFColorProvider.java
> +* Copyright (c) 2000, 2023 IBM Corporation and others.
similar then above this copyright header shouldn't feature IBM. Sorry that I missed that the first time.

2023-04-07 08:37 UTC, azoitl commented
@Destrolaric while your commit fixed the problems with Draw2d and Zest I now see the GEF tests failing because of an issue in the InternalGEFPlugin. I haven't seen this before therefore I'm somehow thinking this could come from your commit. Do you have any idea what is going on here?

2023-04-07 08:55 UTC, Destrolaric commented
@azoitl Initialization of the provider is done from the plugin. I am currently thinking about what causes it to fail.

2023-04-07 11:09 UTC, Destrolaric commented
@azoitl Hmm, are this two tests have failed previously?

2023-04-07 12:22 UTC, azoitl commented
> @azoitl Hmm, is these two tests failed previously?

I think so. We had several failing test before you started working on GEF Classic. I would look later into them.

2023-04-07 12:24 UTC, azoitl approved these changes
thx for the updates they look good.

2023-04-07 12:25 UTC, merged