Typify MultiValueMap and fix warnings in AutomaticRouter
eclipse/gef-classic pull request #320
Opened 2023-12-14 20:25 UTC by ptziegler

The MultiValueMap used to be backed by a map with either a list or a single object as value.

This part has been adapted so that the map always contains a list of values. While this adds a small overhead when filling the map, it should in return reduce the overhead when calling the getter for values with only a single element.

Reduces the total amount of warnings by ~20.

2023-12-14 21:13 UTC, azoitl requested changes
This is also a class I always wanted to tackle. Great that you did it.

2023-12-15 05:09 UTC, ptziegler commented on org.eclipse.draw2d/src/org/eclipse/draw2d/internal/MultiValueMap.java
> -				v.add(value);
oops

2023-12-15 07:36 UTC, azoitl commented on org.eclipse.draw2d/src/org/eclipse/draw2d/internal/MultiValueMap.java
> -				v.add(value);
easy to miss.

2023-12-15 07:37 UTC, azoitl approved these changes

2023-12-15 07:37 UTC, merged

2023-12-15 16:05 UTC, ptziegler commented
#155